# SQL Matic Configuration

# Application settings
app:
  name: "SQL Matic"
  port: 8000
  debug: true
  environment: "development"

# Database settings for application
database:
  path: "sample.db"
  pool_size: 5
  timeout: 30
  type: sqlite

# Query Database settings
query_db:
  path: "../user_files/sakila.db"
  max_rows_return: 1000
  timeout: 30
  enable_write: false  # Whether to allow write operations
  allowed_tables: []  # Empty list means all tables
  excluded_tables: []  # Tables to exclude from queries
  sample_rows: 5  # Number of sample rows to show in schema info
  cache_schema: true
  cache_duration: 3600  # Cache duration in seconds

# API settings
api:
  prefix: /api
  version: v1

# CORS settings
cors:
  origins: ["*"]
  credentials: true
  methods: ["*"]
  headers: ["*"]

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
  file: "tools/app.log"  # Centralized log location
  max_size: 10485760  # 10MB in bytes
  backup_count: 5
  console: true  # Whether to output logs to console

# Agent settings
agent:
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 1000
  timeout: 60
  retries: 3
  query_prefix: "-- This query was generated by SQL Matic\n"
  max_iterations: 3  # Maximum number of query refinement iterations

# Security settings
security:
  secret_key: placeholder_replace_in_production
  token_expiration: 86400  # 24 hours in seconds
  algorithm: HS256

# Storage settings
storage:
  user_files_dir: user_files
  max_upload_size: 104857600  # 100MB
  allowed_extensions:
    - .db
    - .sqlite
    - .sqlite3
