# SQL Matic Configuration

# Application settings
app:
  name: SQL Matic
  port: 8000
  debug: true
  environment: development  # development, testing, production

# Database settings
database:
  path: user_files/database.db
  pool_size: 5
  timeout: 30

# Query Database settings
query_db:
  type: sqlite  # sqlite, mysql, postgresql, etc.
  path: user_files/query_database.db  # For SQLite
  connection_string: ""  # For other database types
  max_rows_return: 1000
  timeout: 30
  enable_write: false  # Whether to allow write operations
  allowed_tables: []  # Empty list means all tables
  excluded_tables: []  # Tables to exclude from queries
  sample_rows: 5  # Number of sample rows to show in schema info
  cache_schema: true
  cache_duration: 3600  # Cache duration in seconds

# API settings
api:
  prefix: /api
  version: v1

# CORS settings
cors:
  origins:
    - "*"  # In production, specify exact origins
  credentials: true
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  headers:
    - Content-Type
    - Authorization

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/app.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Agent settings
agent:
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 1000
  timeout: 60
  retries: 3
  query_prefix: "-- This query was generated by SQL Matic\n"
  max_iterations: 3  # Maximum number of query refinement iterations

# Security settings
security:
  secret_key: placeholder_replace_in_production
  token_expiration: 86400  # 24 hours in seconds
  algorithm: HS256

# Storage settings
storage:
  user_files_dir: user_files
  max_upload_size: 10485760  # 10MB
  allowed_extensions:
    - .db
    - .sqlite
    - .sqlite3
